openapi: 3.0.4
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: >-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification. 
    You can find out more about

    Swagger at [https://swagger.io](https://swagger.io). In the third iteration
    of the pet store, we've switched to the design first approach!

    You can now help us improve the API whether it's by making changes to the
    definition itself or to the code.

    That way, with time, we can improve the API in general, and expose some of
    the new features in OAS3.


    Some useful links:

    - [The Pet Store
    repository](https://github.com/swagger-api/swagger-petstore)

    - [The source API definition for the Pet
    Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: https://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.27
servers:
  - url: /api/v3
security: []
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: https://swagger.io
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: https://swagger.io
  - name: user
    description: Operations about user
paths:
  /pet:
    $ref: ./paths/pet.yaml
  /pet/findByStatus:
    $ref: ./paths/pet-findByStatus.yaml
  /pet/findByTags:
    $ref: ./paths/pet-findByTags.yaml
  /pet/{petId}:
    $ref: ./paths/pet-petId.yaml
  /pet/{petId}/uploadImage:
    $ref: ./paths/pet-petId-uploadImage.yaml
  /store/inventory:
    $ref: ./paths/store-inventory.yaml
  /store/order:
    $ref: ./paths/store-order.yaml
  /store/order/{orderId}:
    $ref: ./paths/store-order-orderId.yaml
  /user:
    $ref: ./paths/user.yaml
  /user/createWithList:
    $ref: ./paths/user-createWithList.yaml
  /user/login:
    $ref: ./paths/user-login.yaml
  /user/logout:
    $ref: ./paths/user-logout.yaml
  /user/{username}:
    $ref: ./paths/user-username.yaml
components:
  schemas:
    $ref: ./components/schemas.yaml
  requestBodies:
    $ref: ./components/requestBodies.yaml
  securitySchemes:
    $ref: ./components/securitySchemes.yaml
